baseURL = ""
languageCode = "en"
defaultContentLanguage = "en"
title = "Hallo"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Benson Yeung"

[params]

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "bensonyeung013@gmail.com"

    [[params.links]]
        icon = "instagram"
        title = "instagram"
        url = "https://www.instagram.com/bennsoonnn/"
